### ISSUE TITLE
bad rng

### ISSUE THREAD

**Issue by masonhobbs** [masonhobbs/CowboyBot#1]
always rolls 1

**Comment by masonhobbs** [comment]
ĭ̵̺̫̎́̿͊͘͝ ̸̢̮̖̫̟̣̟̟̍̌̿̏̈́͋́̅͌̕͜͜͜ẉ̵̢͇̘̥̱̜̩͙̙̞̹̄̀̃͛͘i̷̡͎͍̤̰̺͎͔̘̦̝͇̐͆̔̀̉̓͂͋̈̿̒́͌́̇l̴̃̒͐̇̔̽̂ͅļ̷͚̖͇̣̤̟̦͉͙̯̀̀͑ ̸̨̘̘̫͒̂͒͌̈́͒͝͝n̵̺͇͇͚͙̖͈̽̏̔͂̄̄́̾̚̚̚͠o̵̬͕͙̮̗̫̪͍̜̖͈͑̓̒̀̈́̄̆̈́̉͠t̷̝͓̫̩̙̬̰͈̭̆͜͜͜ ̸̡̝̜̘͕̦̝̟̥͚͇͇̓̆͂̀̑̇̎̑̾̔̃̎̋̕ͅb̷̡̨͔͍̻̬͕̦͖̟͎͉͍̊͐̊̓̕ͅȇ̷̼̝̣̻̔̂̔́̃͝͠ͅ ̶̛̬̘̟̜͙̞̯̲͔̱͕͈̪̹͑̿͒̅̄̀̏̐͝ͅḓ̷̢̗͇͎̙͎̘͖̝͈̩̙̬̿̃̈́̈̎̈́̑̊͝e̴̝̎͆͌̽͂̅̎̄̈̎͘͝͠͝s̷̤̼̜̩̪̝̮͓͈̟̭͕̅ť̷̨̧̯̳̳̻̮͙̫͔̭̜̔͊̒́̎ͅr̵̨̢̘͖̺̟̬̟̲̣͕͙̯̪̳̓̉̈́̔͆̈́̒͊o̸͖̹̺̘͖͓̱̿̀͝ỵ̷̢̏ȩ̶̨̼͎̦͕̯̻͓̬͎̗̓͌̽̿̐̔̆͗͊̾̇d̴̡̬͈͇̙͕̺̭̱̗̔͗̉̈̇̂̈́̓̿͝

**Comment by PacosMartini** [comment]
Doesn't always roll 20, pls fix

**Comment by masonhobbs** [comment]
ĭ̵̺̫̎́̿͊͘͝ ̸̢̮̖̫̟̣̟̟̍̌̿̏̈́͋́̅͌̕͜͜͜ẉ̵̢͇̘̥̱̜̩͙̙̞̹̄̀̃͛͘i̷̡͎͍̤̰̺͎͔̘̦̝͇̐͆̔̀̉̓͂͋̈̿̒́͌́̇l̴̃̒͐̇̔̽̂ͅļ̷͚̖͇̣̤̟̦͉͙̯̀̀͑ ̸̨̘̘̫͒̂͒͌̈́͒͝͝n̵̺͇͇͚͙̖͈̽̏̔͂̄̄́̾̚̚̚͠o̵̬͕͙̮̗̫̪͍̜̖͈͑̓̒̀̈́̄̆̈́̉͠t̷̝͓̫̩̙̬̰͈̭̆͜͜͜ ̸̡̝̜̘͕̦̝̟̥͚͇͇̓̆͂̀̑̇̎̑̾̔̃̎̋̕ͅb̷̡̨͔͍̻̬͕̦͖̟͎͉͍̊͐̊̓̕ͅȇ̷̼̝̣̻̔̂̔́̃͝͠ͅ ̶̛̬̘̟̜͙̞̯̲͔̱͕͈̪̹͑̿͒̅̄̀̏̐͝ͅḓ̷̢̗͇͎̙͎̘͖̝͈̩̙̬̿̃̈́̈̎̈́̑̊͝e̴̝̎͆͌̽͂̅̎̄̈̎͘͝͠͝s̷̤̼̜̩̪̝̮͓͈̟̭͕̅ť̷̨̧̯̳̳̻̮͙̫͔̭̜̔͊̒́̎ͅr̵̨̢̘͖̺̟̬̟̲̣͕͙̯̪̳̓̉̈́̔͆̈́̒͊o̸͖̹̺̘͖͓̱̿̀͝ỵ̷̢̏ȩ̶̨̼͎̦͕̯̻͓̬͎̗̓͌̽̿̐̔̆͗͊̾̇d̴̡̬͈͇̙͕̺̭̱̗̔͗̉̈̇̂̈́̓̿͝
